# Generated by Django 2.1.3 on 2018-11-17 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('fraud', 'Fraudulent'), ('suspicious', 'Suspicious'), ('new', 'New'), ('ok', 'Ok'), ('trusted', 'Trusted')], default='new', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers_transactions', to='ontofraud.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers_transactions', to='ontofraud.Wallet'),
        ),
    ]
