# Generated by Django 2.1.3 on 2018-11-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontofraud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payer',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='to_address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
