# Generated by Django 2.1.3 on 2018-11-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontofraud', '0002_auto_20181117_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hashid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
