# Generated by Django 2.1.3 on 2018-11-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontofraud', '0004_auto_20181117_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='asset_name',
        ),
    ]
