# Generated by Django 2.1.3 on 2018-11-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontofraud', '0005_remove_transaction_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
